/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omi;

import java.awt.Label;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author oshan dileep
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    String arr[]={"iA","iK","iQ","iJ","i10","i9","i8","i7","hA","hK","hQ","hJ","h10","h9","h8","h7"
                         ,"rA","rK","rQ","rJ","r10","r9","r8","r7","kA","kK","kQ","kJ","k10","k9","k8","k7"};
          static ArrayList list=new ArrayList<String>();
          ArrayList p1=new ArrayList<String>();
          ArrayList p2=new ArrayList<String>();
          ArrayList p3=new ArrayList<String>();
          ArrayList p4=new ArrayList<String>();
          String card;
          int count;
          char thurumpu;
    public mainMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        count=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDisplay = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtThurumpu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        lblDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDisplay.setText("jLabel1");

        jToggleButton1.setText("Shuffle");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel2.setText("2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setText("4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel8.setText("8");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel5.setText("5");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setText("1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setText("3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel7.setText("7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel6.setText("6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jLabel9.setText("YOU");

        jLabel10.setText("Player2");

        jLabel11.setText("Player4");

        jLabel12.setText("Player3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(296, 296, 296))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(65, 65, 65)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        txtThurumpu.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDisplay)
                                .addGap(9, 9, 9)))
                        .addGap(72, 72, 72)
                        .addComponent(txtThurumpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblDisplay)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(txtThurumpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Icon ico,ico2,ico3,ico4,ico5,ico6,ico7,ico8,ico9;
        double x=32*Math.random();
          
        arrToList();
        shuffle(p1,"player 1");
        shuffle(p2,"player 2");
        shuffle(p3,"player 3");
        shuffle(p4,"player 4");
        thurumpu=txtThurumpu.getText().charAt(0);
        
        jLabel1.setText(p1.get(0)+"");
        ico=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(0)+".gif");
        jLabel1.setIcon(ico);
        ico2=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(1)+".gif");
        jLabel2.setIcon(ico2);
        ico3=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(2)+".gif");
        jLabel3.setIcon(ico3);
        ico4=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(3)+".gif");
        jLabel4.setIcon(ico4);
        ico5=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(4)+".gif");
        jLabel5.setIcon(ico5);
        ico6=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(5)+".gif");
        jLabel6.setIcon(ico6);
        ico7=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(6)+".gif");
        jLabel7.setIcon(ico7);
        ico8=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+p1.get(7)+".gif");
        jLabel8.setIcon(ico8);
        
          
          /*int pack[]=new int[32];
          String packPlayer[]=new String[8];
          for(int i=0;i<packPlayer.length;i++)
          {
              //pack[i]=(int)(32*Math.random());
              packPlayer[i]=arr[(int)(31*Math.random())];
              System.out.println(""+packPlayer[i]);
          }*/
          
        int ran=(int)x;
        /*if(ran<8)
            {
                lblDisplay.setText("Iskooppa "+arr[ran]);
            }
        else if(ran>=8 && ran<16)
            lblDisplay.setText("Heart "+arr[ran-7]);*/
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        card=putCard(jLabel1, p1, 0);
        AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel2, p1, 1);
        AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel3, p1, 2);
          AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel4, p1, 3);
         AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel5, p1, 4);
        AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel6, p1, 5);
          AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
          
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel7, p1, 6);
          AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         card=putCard(jLabel8, p1, 7);
          AI(p2,jLabel10);
        AI(p3,jLabel12);
        AI(p4,jLabel11);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }
    public void arrToList()
    {
        for(int i=0;i<arr.length;i++)
            {
              list.add(arr[i]);
            }
    }
    public static void shuffle(ArrayList li,String player)
    {
       
        int x;
        for(int i=0;i<8;i++)
        {
            try{
          x=(int)(31*Math.random());
          li.add(list.get(x));
          list.remove(x);
            System.out.println(player+" -"+li.get(i));
            }catch(IndexOutOfBoundsException ie){
                i=i-1;
               // continue;
            }
        }
    }
    
    public String putCard(JLabel l,ArrayList al,int Remove)
    {
         count++;
        Icon ico;
        String ret;
        al.size();
        ret=(String)al.get(Remove);
        ico=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+al.get(Remove)+".gif");
        jLabel9.setIcon(ico);
        jLabel9.setVisible(true);
        l.setVisible(false);
        //al.add(Remove, " ");
        if(count==8)
        {
            for(int i=0;i<al.size();i++)
            {
                al.remove(i);
            }
        }
        
        return ret;
    }
    public void AI(ArrayList player,JLabel lbl)
    {
        String pCard="";
        boolean CardFound=false;
        Icon ico;
        for(int i=0;i<player.size();i++){
             if(card.charAt(0)== ((player.get(i)+"").charAt(0)) ){
                 pCard=(player.get(i)+"");
                  player.remove(i);
                 player.add(i, " ");
                 CardFound=true;
                 break;
             }
             
        }
        if(!CardFound){
            for(int i=0;i<player.size();i++){
             if(((player.get(i)+"").charAt(0))==thurumpu ){
                 pCard=(player.get(i)+"");
                 player.remove(i);
                 player.add(i, " ");
                 CardFound=true;
                 break;
             }
            }
        }
        if(!CardFound){
            for(int i=0;i<player.size();i++){
             if(((player.get(i)+"").charAt(0))=='r' ||((player.get(i)+"").charAt(0))=='i' || ((player.get(i)+"").charAt(0))=='h' || ((player.get(i)+"").charAt(0))=='k' ){
                 pCard=(player.get(i)+"");
                  player.remove(i);
                 player.add(i, " ");
                 CardFound=true;
                 break;
             }
            }
        }
        System.out.println("Lastly "+pCard);
        ico=new ImageIcon("C:\\Users\\oshan dileep\\Documents\\NetBeansProjects\\omi\\src\\images\\"+pCard+".gif");
        lbl.setIcon(ico);
        lbl.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JTextField txtThurumpu;
    // End of variables declaration//GEN-END:variables
}
